"""
Django settings for chinari_system project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
default_secret_key = 'django-insecure-ucxy^9dlksmz5g(rgtwsftumwmiwfu(pxgsro*tfpqo(r+v_47'
SECRET_KEY = os.getenv('SECRET_KEY')
if SECRET_KEY is None:
    if 'VERCEL' in os.environ:
        raise RuntimeError('SECRET_KEY must be set when running on Vercel.')
    SECRET_KEY = default_secret_key

# SECURITY WARNING: don't run with debug turned on in production!
if 'VERCEL' in os.environ:
    DEBUG = os.getenv('DJANGO_DEBUG', '0') == '1'
else:
    DEBUG = os.getenv('DJANGO_DEBUG', '1') == '1'

ALLOWED_HOSTS = []
vercel_url = os.getenv('VERCEL_URL')
if vercel_url:
    ALLOWED_HOSTS.append(vercel_url)
else:
    if 'VERCEL' not in os.environ:
        ALLOWED_HOSTS.extend(['localhost', '127.0.0.1'])
extra_hosts = os.getenv('ALLOWED_HOSTS')
if extra_hosts:
    ALLOWED_HOSTS.extend([host.strip() for host in extra_hosts.split(',') if host.strip()])
if not ALLOWED_HOSTS and 'VERCEL' in os.environ:
    raise RuntimeError('ALLOWED_HOSTS must be set when running on Vercel.')

CSRF_TRUSTED_ORIGINS = []
if vercel_url:
    CSRF_TRUSTED_ORIGINS.append(f'https://{vercel_url}')
extra_csrf = os.getenv('CSRF_TRUSTED_ORIGINS')
if extra_csrf:
    CSRF_TRUSTED_ORIGINS.extend([origin.strip() for origin in extra_csrf.split(',') if origin.strip()])


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'tailwind',
    'theme',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'vendors',
    'products',
    'inventory',
    'sales.apps.SalesConfig',
    'payments',



]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chinari_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chinari_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "theme" / "static",
]
STATIC_ROOT = BASE_DIR / "static"
# Tailwind settings
TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = ['127.0.0.1']  # Required for django-browser-reload if used
